################################################################################
# Entry point for the CV generation process                                    #
################################################################################
# The following Makefile wraps all commands required to generate the CV from   #
# the source data and template, as well as helpers and prerequisites.          #
# To get started run `make`, or `make [command]` to run a specific command.    #
################################################################################
# Full source & links to generated assets is at: https://github.com/Daniel-wambua/cv #
# Licensed under the MIT License, ⓒ Daniel Wambua 2024 <danielwambua.com>       #
################################################################################

# Specify that the targets are not files
.PHONY: all install validate generate compile markdown copy_to_web clean clean_tex watch web_install web web_dev

# Define variables for common paths
PYTHON := $(shell which python3 2>/dev/null || which python)
REQUIREMENTS := lib/requirements.txt
SCHEMA := schema.json
RESUME := resume.yml
TEMPLATE := template.jinja
OUTPUT_TEX := tex/resume.tex
OUTPUT_PDF := out/Daniel-Wambua-CV.pdf
STATIC_PDF := web/static/downloads/Daniel-Wambua-CV.pdf
OUTPUT_MD := out/Daniel-Wambua-CV.md

# Default target. Install deps, validate, generate, compile, emit markdown,
# then publish the PDF into the web app's static downloads directory.
# This means that CI/CD only needs to call `make all` and then build/deploy the web app.
all: install clean validate generate compile markdown copy_to_web

# Install required Python packages
install:
	$(PYTHON) -m pip install -r $(REQUIREMENTS)

# Validate the resume JSON against the schema
validate:
	$(PYTHON) lib/validate.py --schema $(SCHEMA) --resume $(RESUME) --template $(TEMPLATE)

# Generate the LaTeX file from the template and JSON data
generate:
	$(PYTHON) lib/generate.py --resume $(RESUME) --template $(TEMPLATE) --output $(OUTPUT_TEX)

# Compile the LaTeX file into a PDF
compile:
	$(PYTHON) ./lib/compile.py --input $(OUTPUT_TEX) --output $(OUTPUT_PDF)

# Convert the resume to markdown
markdown:
	$(PYTHON) lib/markdown.py --input $(RESUME) --output $(OUTPUT_MD)

# Copy the freshly built PDF to the web app's public downloads directory
# Ensures that `/api/pdf` serves this exact artifact by default
copy_to_web: $(OUTPUT_PDF)
	mkdir -p $(dir $(STATIC_PDF))
	cp -f $(OUTPUT_PDF) $(STATIC_PDF)

# Clean up auxiliary LaTeX files
clean: clean_tex
	rm -f $(OUTPUT_PDF) $(OUTPUT_MD) $(OUTPUT_TEX)

# Clean only the auxiliary files generated by LaTeX
clean_tex:
	rm -f tex/*.aux tex/*.log tex/*.out tex/*.toc tex/*.fls tex/*.fdb_latexmk tex/*.synctex.gz

# Helper target to watch for changes and rebuild everything
watch:
	ls $(REQUIREMENTS) $(SCHEMA) $(RESUME) $(TEMPLATE) | entr -c make all


web_install:
	cd web && npm install

web: web_install
	cd web && npm run build && npm run preview

web_dev: web_install
	cd web && npm run dev
