name: Generate PDF

on:
  workflow_dispatch:
  push:
    paths:
      - 'tex/**'
    tags:
      - '*'
  pull_request:
    paths:
      - 'tex/**'

env:
  PDF_NAME: Alicia-Sykes-CV.pdf

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v2

    - name: 🐍 Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: 📦 Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd lib && pip install -r requirements.txt

    - name: 📝 Install LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full latexmk

    - name: 📄 Generate PDF
      run: make

    - name: 📤 Upload PDF artifact
      uses: actions/upload-artifact@v2
      with:
        name: resume-pdf
        path: out/${{ env.PDF_NAME }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v2

    - name: 📝 Install LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full latexmk

    - name: 📦 Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd lib && pip install -r requirements.txt

    - name: 📄 Generate PDF
      run: make

    - name: 📤 Upload release asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: out/${{ env.PDF_NAME }}
        asset_name: ${{ env.PDF_NAME }}
        asset_content_type: application/pdf

    - name: 📄 Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_TOKEN || secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: "Generated CV PDF for release ${{ github.ref }}"
        draft: true
        prerelease: false

    - name: 📤 Upload PDF to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: out/${{ env.PDF_NAME }}
        asset_name: ${{ env.PDF_NAME }}
        asset_content_type: application/pdf
